### ISSUE TITLE
typo in ConstraintsRelatedToAccesAndUse

### ISSUE THREAD

**Issue by pvgenuchten** [SEMICeu/iso-19139-to-dcat-ap#11]
no license is added due to typo in (missing 's')
https://github.com/SEMICeu/iso-19139-to-dcat-ap/blob/e7aa2d802f6e337ffce64c9167c66b835916f421/iso-19139-to-dcat-ap.xsl#L2444

**Comment by andrea-perego** [comment]
Thanks for reporting this bug, @pvgenuchten .

Fix done via PR https://github.com/SEMICeu/iso-19139-to-dcat-ap/issues/11

Could you please check, and let me know if you are happy with this fix?
