### ISSUE TITLE
Add OpenAPI 3+ Spec

### ISSUE THREAD

**Issue by ioggstream** [SEMICeu/iso-19139-to-dcat-ap#20]
## I wish

this API to provide an OAS 3+ specification

**Comment by akuckartz** [comment]
Why?

**Comment by andrea-perego** [comment]
@ioggstream , I suggest you submit a draft OAS description via a PR, so to have something tangible to review.

**Comment by jakubklimek** [comment]
As the API is no longer maintaned, closing.
