### ISSUE TITLE
dct:spatial should have dct:Location content

### ISSUE THREAD

**Issue by pvgenuchten** [SEMICeu/iso-19139-to-dcat-ap#27]
I had challenges validating dct:spatial in a dcat validator, for me below xml worked:

```
<dct:spatial>
         <dct:Location rdf:about="https://example.com/7273cd98-5af0-45e5-b31a-8b8ac3a5875d#spatial">
            <dcat:bbox rdf:datatype="http://www.opengis.net/ont/geosparql#wktLiteral"><![CDATA[POLYGON((14.52 69.06,24.00 69.06,24.00 65.29,14.52 65.29,14.52 69.06))]]></dcat:bbox>
         </dct:Location>
      </dct:spatial>
```

**Comment by andrea-perego** [comment]
Thanks for reporting this issue, @pvgenuchten .

Actually, this problem should have been fixed by PR https://github.com/SEMICeu/iso-19139-to-dcat-ap/pull/23 .

Could you please check if, by using the current version of the XSLT, you still get the same validation error?

**Comment by andrea-perego** [comment]
@pvgenuchten , is this problem now solved? Can we close this issue?
