### ISSUE TITLE
Tag each new version

### ISSUE THREAD

**Issue by arbakker** [SEMICeu/iso-19139-to-dcat-ap#30]
It took me a while to find out what version of dcat-ap the current version of the XSLT generates. This could be improved by tagging (or creating a release) each new released version in this repository. This makes it easy for users to link a release to a specific commit. Right now this kind of awkard. I suppose right now the [edit commit](https://github.com/SEMICeu/iso-19139-to-dcat-ap/commits/master/CHANGELOG.md) of the CHANGELOG.md represents the version/release, but it is not very explicit. So for instance, right now [this commit]( https://github.com/SEMICeu/iso-19139-to-dcat-ap/tree/a28914f16428b7f61d3c117b7fa0ae2b41cd828b) represents version 2.7.

With the proposed change the version is also reflected in the url (works since there is already one release; [v1.13](https://github.com/SEMICeu/iso-19139-to-dcat-ap/releases/tag/v1.13)): `https://raw.githubusercontent.com/SEMICeu/iso-19139-to-dcat-ap/v1.13/iso-19139-to-dcat-ap.xsl`.

**Comment by andrea-perego** [comment]
Thanks for raising this issue, @arbakker .

The policy adopted so far (but not explicitly stated) is that the XSLT in the `master` branch always implements the mappings defined in the latest version of GeoDCAT-AP. Releases are created when work starts to implement a new version of GeoDCAT-AP.

So, the current XSLT in the `master` branch implements GeoDCAT-AP 2, whereas release 1.13 implements GeoDCAT-AP 1.

Does this make sense to you?

Meanwhile, I'll revise the documentation to explain the current policy.

**Comment by andrea-perego** [comment]
Relevant revisions implemented via PR https://github.com/SEMICeu/iso-19139-to-dcat-ap/pull/33 (yet to be merged).
