### ISSUE TITLE
XSLT version 2.0 now required

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/iso-19139-to-dcat-ap#49]
As part of #42, XSLT was bumped to 2.0. The [XSLT 2.0](https://www.w3.org/TR/xslt20/) spec is from 2007, nevertheless, some simpler libraries such as `lxml` (#48) do not support it. This issue is for discussion of how big a problem this is and whether we should invest effort into downgrading to XSLT 1.0 and developing XSLT 1.0 workarounds for the missing XSLT 2.0 features.

**Comment by streino** [comment]
How are such decisions usually handled within SEMIC, and what sort of timeframe can we expect for a resolution?

No pressure of course, but it'd help to have an idea of the timing to plan how we'll deal with this on our side. Thanks!

**Comment by jakubklimek** [comment]
The public review of GeoDCAT-AP 3.0.0, including the updated XSLT, will start momentarily and go until the end of September. This is the timeframe when anyone can argue for, e.g. keeping XSLT 1.0. The decision will be taken then, and applied for the official release.

**Comment by jakubklimek** [comment]
Since no additional feedback was given, closing.
