### ISSUE TITLE
xml syntax vcard:hasTelephone

### ISSUE THREAD

**Issue by pvgenuchten** [SEMICeu/iso-19139-to-dcat-ap#8]
[Swedish validator](https://registrera.oppnadata.se/toolkit/validate) fails at 

https://github.com/SEMICeu/iso-19139-to-dcat-ap/blob/e7aa2d802f6e337ffce64c9167c66b835916f421/iso-19139-to-dcat-ap.xsl#L1507

expects hasTelephone as https://www.w3.org/TR/vcard-rdf/#Examples

```xml
        <vcard:hasTelephone rdf:parseType="Resource">
          <vcard:hasValue rdf:resource="tel:+61755555555"/>
          <rdf:type rdf:resource="http://www.w3.org/2006/vcard/ns#Home"/>
          <rdf:type rdf:resource="http://www.w3.org/2006/vcard/ns#Voice"/>
        </vcard:hasTelephone>
```

**Comment by andrea-perego** [comment]
Thanks for reporting this issue, @pvgenuchten .

I guess this is the pattern/template defined in the Swedish profile of DCAT-AP (I don't know if other DCAT-AP profiles recommend the same one). 

If this is the case, this issue should be preferably addressed by a custom version of the GeoDCAT-AP XSLT, implementing the requirements of the Swedish profile.

/cc @matthiaspalmer

**Comment by pvgenuchten** [comment]
Ok, clear answer

**Comment by matthiaspalmer** [comment]
The DCAT-AP specifications (both earlier and latest) are rather vague regarding how to express the vcard:Kind of the dcat:contactPoint. In the Swedish profile we thought it better to provide guidance for implementors on which properties to use, e.g. which properties to use and weather to use the n-ary or direct properties.

Clearly, when you implement a mapping you have to decide, which is apparent in the transform mentioned XSLT file. And when you build something like a portal you typically need to either harmonize or understand a lot of different cases. And apparently we made different decisions in the Swedish DCAT-AP compared to the Inspire to dcat XSLT.

I just checked the German and Norwegian DCAT-AP profiles, they do not seem to provide any guidance on this unfortunately. I guess a deeper look is required to see if there is a majority rule to gravitate towards in the future.
