### ISSUE TITLE
rdf:resource expected, has rdf:about

### ISSUE THREAD

**Issue by pvgenuchten** [SEMICeu/iso-19139-to-dcat-ap#9]
At https://github.com/SEMICeu/iso-19139-to-dcat-ap/blob/e7aa2d802f6e337ffce64c9167c66b835916f421/iso-19139-to-dcat-ap.xsl#L1975 seems reference is made to a catalogRecord, use of rdf:about seems wrong, expected rdf:resource as well as https://github.com/SEMICeu/iso-19139-to-dcat-ap/blob/e7aa2d802f6e337ffce64c9167c66b835916f421/iso-19139-to-dcat-ap.xsl#L1992

**Comment by andrea-perego** [comment]
Actually, `@rdf:about` is correct here, as it specifies the URI of a class instance (`dcat:CatalogRecord`).

It should have been `@rdf:resource` if used with a property - e.g.:

````xml
...
  <foaf:isPrimaryTopicOf rdf:resource="xyz"/>
...

<dcat:CatalogRecord rdf:about="xyz"/>
````

**Comment by pvgenuchten** [comment]
Ok, thanx for pointing
